/**
 * Service-worker registration glue.
 *
 * Uses the framework-agnostic `virtual:pwa-register` entry point from
 * vite-plugin-pwa rather than the Svelte-specific helper so the reactive
 * state matches the rest of the app (runes, not Svelte stores).
 *
 * Two pieces of UI feedback come out of this:
 *
 * 1. `offlineReady` — set to true the first time the service worker
 *    finishes precaching the app shell. The banner shows "Ready to use
 *    offline." once.
 * 2. `needRefresh` — set when a newer service worker is waiting. Calling
 *    `applyUpdate()` activates it and reloads the page.
 *
 * In dev (no service worker), `register()` is a no-op so we can `import`
 * this module unconditionally.
 */

// `virtual:pwa-register` is generated by vite-plugin-pwa at build time.
// In dev with devOptions.enabled=false it still resolves to a no-op shim.

export class PwaState {
  offlineReady = $state(false);
  needRefresh = $state(false);

  private updateSW: ((reload?: boolean) => Promise<void>) | null = null;

  /**
   * Register the service worker. Returns immediately; the SW download +
   * activation happens in the background. Safe to call multiple times
   * (subsequent calls are no-ops).
   *
   * In dev mode, also unregisters any pre-existing service workers. SWs
   * survive across dev/preview/prod sessions on the same origin, so a
   * leftover SW from a prior `npm run preview` (or an installed PWA)
   * will silently intercept fetches under `npm run dev` and serve stale
   * cached assets. The symptom is hard-to-debug layout/JS weirdness
   * because CSS scope hashes from the cached build don't match the
   * fresh JS being served by Vite. Auto-unregistering eliminates that
   * class of bug.
   */
  async register(): Promise<void> {
    if (this.updateSW !== null) return;
    if (typeof window === 'undefined') return;

    if (import.meta.env.DEV) {
      await unregisterAll();
      return;
    }

    // Dynamic import so the bundler can drop this entirely in non-PWA builds.
    const { registerSW } = await import('virtual:pwa-register');
    this.updateSW = registerSW({
      immediate: true,
      onOfflineReady: () => {
        this.offlineReady = true;
      },
      onNeedRefresh: () => {
        this.needRefresh = true;
      },
      onRegisterError: (err) => {
        console.warn('Service worker registration failed:', err);
      },
    });
  }

  /**
   * Activate the waiting service worker and reload. Called from the banner's
   * "Reload" button. The `true` argument tells vite-plugin-pwa to reload the
   * page after the new SW takes control.
   */
  async applyUpdate(): Promise<void> {
    if (this.updateSW) await this.updateSW(true);
  }

  dismissOfflineReady(): void {
    this.offlineReady = false;
  }
}

export function createPwaState(): PwaState {
  return new PwaState();
}

/**
 * Unregister every service worker on this origin and purge their caches.
 * Called in dev mode so a leftover SW from a prior preview/prod session
 * can't intercept dev-server fetches with stale assets. Logs a one-time
 * notice when something is actually unregistered, so the developer
 * understands why the page may have just behaved oddly on the previous
 * load.
 */
async function unregisterAll(): Promise<void> {
  if (!('serviceWorker' in navigator)) return;
  try {
    const regs = await navigator.serviceWorker.getRegistrations();
    if (regs.length === 0) return;
    await Promise.all(regs.map((r) => r.unregister()));
    if ('caches' in window) {
      const names = await caches.keys();
      await Promise.all(names.map((n) => caches.delete(n)));
    }
    console.info(
      `[pwa] Unregistered ${regs.length} pre-existing service worker(s) and cleared caches ` +
        `(dev mode). Reload once more if you see stale assets.`,
    );
  } catch (err) {
    console.warn('[pwa] Failed to unregister pre-existing service workers:', err);
  }
}
