/**
 * Service-worker registration glue.
 *
 * Uses the framework-agnostic `virtual:pwa-register` entry point from
 * vite-plugin-pwa rather than the Svelte-specific helper so the reactive
 * state matches the rest of the app (runes, not Svelte stores).
 *
 * Two pieces of UI feedback come out of this:
 *
 * 1. `offlineReady` — set to true the first time the service worker
 *    finishes precaching the app shell. The banner shows "Ready to use
 *    offline." once.
 * 2. `needRefresh` — set when a newer service worker is waiting. Calling
 *    `applyUpdate()` activates it and reloads the page.
 *
 * In dev (no service worker), `register()` is a no-op so we can `import`
 * this module unconditionally.
 */

// `virtual:pwa-register` is generated by vite-plugin-pwa at build time.
// In dev with devOptions.enabled=false it still resolves to a no-op shim.

export class PwaState {
  offlineReady = $state(false);
  needRefresh = $state(false);

  private updateSW: ((reload?: boolean) => Promise<void>) | null = null;

  /**
   * Register the service worker. Returns immediately; the SW download +
   * activation happens in the background. Safe to call multiple times
   * (subsequent calls are no-ops).
   */
  async register(): Promise<void> {
    if (this.updateSW !== null) return;
    if (typeof window === 'undefined') return;
    // Dynamic import so the bundler can drop this entirely in non-PWA builds.
    const { registerSW } = await import('virtual:pwa-register');
    this.updateSW = registerSW({
      immediate: true,
      onOfflineReady: () => {
        this.offlineReady = true;
      },
      onNeedRefresh: () => {
        this.needRefresh = true;
      },
      onRegisterError: (err) => {
        console.warn('Service worker registration failed:', err);
      },
    });
  }

  /**
   * Activate the waiting service worker and reload. Called from the banner's
   * "Reload" button. The `true` argument tells vite-plugin-pwa to reload the
   * page after the new SW takes control.
   */
  async applyUpdate(): Promise<void> {
    if (this.updateSW) await this.updateSW(true);
  }

  dismissOfflineReady(): void {
    this.offlineReady = false;
  }
}

export function createPwaState(): PwaState {
  return new PwaState();
}
